version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPOSITORY: "devops-project"
    IMAGE_TAG: "springboot-helloworld"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION |
        docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - echo ECR URI is $ECR_URI

  build:
    commands:
      - echo Build started on `date`
      - cd HelloWorld
      - echo Building Docker image...
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - docker push $ECR_URI:$IMAGE_TAG
      - echo Image pushed successfully
      - printf '[{"name":"hellocontainer","imageUri":"%s"}]' $ECR_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - HelloWorld/imagedefinitions.json
