services:
  backend:
    build: ./backend
    ports: ["3001:3001"]
  frontend:
    build: ./frontend
    ports: ["3000:5173"]
    environment:
      BACKEND_URL: http://52.91.198.122:3001
    depends_on: [backend]
