version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPO: "capstone"

phases:

  pre_build:
    commands:
      - echo "========== PRE BUILD =========="
      - aws --version

      # Move to application directory
      - cd Aws-Repo/CapstoneProject/react-node-ecs-v2

      # Get AWS account dynamically
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - ECR_URI=$ECR_REGISTRY/$ECR_REPO

      # Use Git commit as version
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - COMMIT_HASH=${COMMIT_HASH:=latest}

      # Separate frontend/backend tags
      - BACKEND_TAG=backend-$COMMIT_HASH
      - FRONTEND_TAG=frontend-$COMMIT_HASH

      - echo "AWS Account = $AWS_ACCOUNT_ID"
      - echo "ECR repository = $ECR_URI"
      - echo "Backend tag = $BACKEND_TAG"
      - echo "Frontend tag = $FRONTEND_TAG"

      # Login to ECR
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo "========== BUILD =========="
      - echo "Build started on $(date)"

      # BACKEND
      - echo "Building backend..."
      - docker build -t $ECR_URI:$BACKEND_TAG ./backend
      - docker tag $ECR_URI:$BACKEND_TAG $ECR_URI:backend-latest

      # FRONTEND
      - echo "Building frontend..."
      - docker build -t $ECR_URI:$FRONTEND_TAG ./frontend
      - docker tag $ECR_URI:$FRONTEND_TAG $ECR_URI:frontend-latest

  post_build:
    commands:
      - echo "========== POST BUILD =========="

      # Push Backend
      - echo "Pushing backend..."
      - docker push $ECR_URI:$BACKEND_TAG
      - docker push $ECR_URI:backend-latest

      # Push Frontend
      - echo "Pushing frontend..."
      - docker push $ECR_URI:$FRONTEND_TAG
      - docker push $ECR_URI:frontend-latest

      # ECS deployment files
      - echo "Creating ECS image definition files..."

      - printf '[{"name":"Backendapp","imageUri":"%s"}]' "$ECR_URI:$BACKEND_TAG" > imagedefinitions-backend.json

      - printf '[{"name":"Frontendapp","imageUri":"%s"}]' "$ECR_URI:$FRONTEND_TAG" > imagedefinitions-frontend.json

      - echo "Backend image definition:"
      - cat imagedefinitions-backend.json

      - echo "Frontend image definition:"
      - cat imagedefinitions-frontend.json

      - echo "Build completed successfully."

artifacts:
  files:
    - Aws-Repo/CapstoneProject/react-node-ecs-v2/imagedefinitions-backend.json
    - Aws-Repo/CapstoneProject/react-node-ecs-v2/imagedefinitions-frontend.json
  discard-paths: yes
